version: "3"

services:
  api:
    build: backend
    command: npm run dev
    ports:
      - "8081:8081"
    volumes:
      - ./backend:/src/backend
    depends_on:
      - db

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: auth_sys
      MYSQL_ROOT_PASSWORD: 123
    expose:
      - 3306
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
